### ISSUE TITLE
Game crashes when darken background is on

### ISSUE THREAD

**Issue by tomhula** [stuin/RoughlySearchable#1]
When I set darken background: true in the settings (trough rei), and then start typing in the search box, the game crases.
[crash-2020-11-10_14.58.55-client.txt](https://github.com/stuin/RoughlySearchable/files/5517775/crash-2020-11-10_14.58.55-client.txt)

**Comment by stuin** [comment]
Version 2.1.2 is up on curseforge, and should fix the issue.
