### ISSUE TITLE
Roughly searchable is causing my Fabric Instance to crash 

### ISSUE THREAD

**Issue by G93d14** [stuin/RoughlySearchable#6]
https://paste.ee/p/KMxj9

Here's a copy of the error log. I've tried running it with no other mods installed and it still happens

https://paste.ee/p/lWrBr

This is a copy of the error log with just REI, Roughly Searchable, and their dependencies active.

I'm using MultiMC, in case that makes a difference.

**Comment by stuin** [comment]
Someone else had a similar issue, with that version of REI you need to update to RS 2.4.1

**Comment by G93d14** [comment]
It works now, Thanks!
